import { imagepath } from "../assest/Index";


export const Categories = [
    {
        name: 'Burger',
        image: require('../assest/image/burger.png'),
        items: [
            {
                name: 'Classic Burger',
                weight: 120,
                rating: '5.0',
                price: 199,
                isTopOfTheWeek: true,
                image: require('../assest/image/classicburger.png'),
                size: 'Large 8"',
                crust: 'Thick Crust',
                delivery: 25,
                ingredients: [
                    require('../assest/image/flour.png'),
                    require('../assest/image/cheese.png'),
                    require('../assest/image/Sliced-Onion.png'),
                    require('../assest/image/Tomato.png'),
                ],
            },
            {
                name: 'Aloo Tikki Burger',
                weight: 150,
                rating: '4.5',
                price: 99,
                isTopOfTheWeek: false,
                image: require('../assest/image/alootikkiburger.png'),
                size: 'Large 12"',
                crust: 'Thick Crust',
                delivery: 20,
                ingredients: [
                    require('../assest/image/Sliced-Onion.png'),
                    require('../assest/image/Tomato.png'),
                    require('../assest/image/cheese.png'),
                    require('../assest/image/flour.png'),
                ],
            },
            {
                name: 'Biggie Cheese',
                weight: 250,
                rating: '4.2',
                price: 299,
                isTopOfTheWeek: false,
                image: require('../assest/image/biggiecheese.png'),
                size: 'Large 10"',
                crust: 'Thick Crust',
                delivery: 35,
                ingredients: [
                    require('../assest/image/Tomato.png'),
                    require('../assest/image/cheese.png'),
                    require('../assest/image/Sliced-Onion.png'),
                    require('../assest/image/flour.png'),
                ],
            },
        ],
    },
    {
        name: 'Pizza',
        image: require('../assest/image/pepperonipizza.png'),
        items: [
            {
                name: 'Pepperoni Pizza',
                weight: 250,
                rating: '5.0',
                price: 199,
                isTopOfTheWeek: true,
                image: require('../assest/image/pepperonipizza.png'),
                size: 'Large 14"',
                crust: 'Thin Crust',
                delivery: 30,
                ingredients: [
                    require('../assest/image/Tomato.png'),
                    require('../assest/image/cheese.png'),
                    require('../assest/image/Sliced-Onion.png'),
                    require('../assest/image/flour.png'),
                ],
            },
            {
                name: 'Plain Cheese Pizza',
                weight: 300,
                rating: '4.5',
                price: 299,
                isTopOfTheWeek: false,
                image: require('../assest/image/plaincheesepizza.png'),
                size: 'Large 16"',
                crust: 'Thin Cheese',
                delivery: 25,
                ingredients: [
                    require('../assest/image/Sliced-Onion.png'),
                    require('../assest/image/flour.png'),
                    require('../assest/image/cheese.png'),
                    require('../assest/image/Tomato.png'),
                ],
            },
            {
                name: 'Mexican Green Wave',
                weight: 350,
                rating: '4.2',
                price: 499,
                isTopOfTheWeek: false,
                image: require('../assest/image/mexicangreenwave.png'),
                size: 'Large 15"',
                crust: 'Thin Crust',
                delivery: 45,
                ingredients: [
                    require('../assest/image/flour.png'),
                    require('../assest/image/cheese.png'),
                    require('../assest/image/Tomato.png'),
                    require('../assest/image/Sliced-Onion.png'),
                ],
            },
        ],
    },
    {
        name: 'Soft Drinks',
        image: require('../assest/image/softdrinks.png'),
        items: [
            {
                name: 'Coco Cola',
                weight: 200,
                rating: '5.0',
                price: 299,
                isTopOfTheWeek: true,
                image: require('../assest/image/cocacola.png'),
                size: 'Medium Glass',
                crust: 'Small Ice',
                delivery: 10,
                ingredients: [require('../assest/image/cocacola.png')],
            },
            {
                name: 'Orange Juice',
                weight: 500,
                rating: '4.5',
                price: 199,
                isTopOfTheWeek: false,
                image: require('../assest/image/orange.png'),
                size: 'LArge Glass',
                crust: 'Large Ice',
                delivery: 8,
                ingredients: [require('../assest/image/orange.png')],
            },
            {
                name: 'Mango Juice',
                weight: 150,
                rating: '4.2',
                price: 99,
                isTopOfTheWeek: false,
                image: require('../assest/image/mango.png'),
                size: 'Large Glass',
                crust: 'Small Ice',
                delivery: 5,
                ingredients: [require('../assest/image/mango.png')],
            },
        ],
    },
];
