export const imagepath = {
    pizza: require('./image/pizza.png'),
    bigpizza: require('./image/pizzabif.png'),
    location: require('./image/location.png'),
    down: require('./image/dropdown.png'),
    sarch: require('./image/surch.png'),
    banner: require('./image/banner.png'),
    meanu: require('./image/meanu.png'),
    snaks: require('./image/snakes.png'),
    blackloc: require('./image/locationBlack.png'),
    star: require('./image/star.png'),
    blackprofile: require('./image/profileLogoblack.png'),
    momos: require('../assest/image/momos.png'),
    chole: require('../assest/image/chole.png'),
    paner: require('../assest/image/paner.png'),
    ghar: require('../assest/image/ghar.png'),
    Genie: require('../assest/image/Genie.png'),
    Instamart: require('../assest/image/Instamart.png'),
    rail: require('../assest/image/rail.png'),
    thali: require('../assest/image/panjabithali.png'),
    pizzathali: require('../assest/image/pizzathali.png'),
    barbiq: require('../assest/image/barbiq.png'),
    bargarbanner: require('../assest/image/bargarbanner.png'),
    redstar: require('../assest/image/redstar.png'),
    love: require('../assest/image/love.png'),
    setting: require('../assest/image/setting.png'),
    redlike: require('./image/redlike.png'),
    blacklike: require('./image/blacklike.png'),
    gift: require('./image/gift.png'),
    errow: require('./image/errow.png'),
    map: require('./image/map.png'),
    dboy: require('./image/dboy.png'),
    Vectorlove: require('./image/Vectorlove.png'),
    shoppingBag: require('./image/shoppingBag.png'),
    shoppingBag2: require('./image/shoppingBag2.png'),
    back: require('./image/back.png'),
    shoppingcartpng: require('./image/shoppingcartpng.png'),
    link: require('./image/link.png'),
    sahil1: require('./image/sahil1.png'),
    swiper1: require('../database/images/accessories/boultairbass3.png'),
    swiper2: require('../database/images/accessories/boatrockerz3.png'),
    swiper3: require('../database/images/accessories/boatrockerz1.png'),
    right: require('../assest/image/right.png'),
    king:require('../assest/image/king.png')
    
}
export const colorpath = {
    white: '#ffffff',
    black: '#000000',
    green: '#00AC76',
    red: '#C04345',
    blue: '#0043F9',
    backgroundLight: '#F0F0F3',
    backgroundMedium: '#B9B9B9',
    backgroundDark: '#777777',
};

export const COLOURS = {
    white: '#ffffff',
    black: '#000000',
    lightGray: '#B3B4B6',
    accent: '#FFC231',
    accentRed: '#FB5D2E',
    accentPink: '#F96165',
};
